export const TENANT_ROLE_CODES = [
  "OWNER",
  "MANAGER",
  "EMPLOYEE",
  "APPRENTICE",
] as const;

export type TenantRoleCode = (typeof TENANT_ROLE_CODES)[number];

export const ROLE_LABELS: Record<TenantRoleCode, string> = {
  OWNER: "Propriétaire",
  MANAGER: "Gestionnaire",
  EMPLOYEE: "Employé",
  APPRENTICE: "Apprenti",
};

export const ROLE_SCOPE: Record<TenantRoleCode, "TENANT"> = {
  OWNER: "TENANT",
  MANAGER: "TENANT",
  EMPLOYEE: "TENANT",
  APPRENTICE: "TENANT",
};

export const PERMISSION_CODES = [
  "customers.read",
  "customers.write",
  "customers.manage",
  "orders.read",
  "orders.write",
  "orders.manage",
  "measurements.read",
  "measurements.write",
  "stock.read",
  "stock.write",
  "fabrics.read",
  "fabrics.write",
  "appointments.read",
  "appointments.write",
  "payments.read",
  "payments.write",
  "payments.cancel",
  "receipts.read",
  "receipts.issue",
  "team.read",
  "team.manage",
  "tenant.settings",
  "subscriptions.view",
  "reports.read",
  "files.read",
  "files.write",
  "sync.read",
  "sync.write",
  "audit.read",
] as const;

export type PermissionCode = (typeof PERMISSION_CODES)[number];

export function isPermissionCode(value: string): value is PermissionCode {
  return (PERMISSION_CODES as readonly string[]).includes(value);
}

export const PERMISSION_LABELS: Record<PermissionCode, string> = {
  "customers.read": "Consulter les clients",
  "customers.write": "Créer / modifier des clients",
  "customers.manage": "Archiver / restaurer (soft)",
  "orders.read": "Consulter les commandes",
  "orders.write": "Créer / modifier les commandes",
  "orders.manage": "Gérer les commandes sensibles",
  "measurements.read": "Consulter les mesures",
  "measurements.write": "Saisir / modifier les mesures",
  "stock.read": "Consulter le stock",
  "stock.write": "Enregistrer les mouvements",
  "fabrics.read": "Consulter les tissus",
  "fabrics.write": "Gérer le référentiel tissus",
  "appointments.read": "Consulter les rendez-vous",
  "appointments.write": "Gérer les rendez-vous",
  "payments.read": "Consulter les paiements",
  "payments.write": "Encaisser un paiement",
  "payments.cancel": "Annuler un paiement",
  "receipts.read": "Consulter les reçus",
  "receipts.issue": "Émettre un reçu",
  "team.read": "Consulter l'équipe",
  "team.manage": "Gérer l'équipe (inviter, rôles)",
  "tenant.settings": "Paramétrer le workspace",
  "subscriptions.view": "Voir l'abonnement",
  "reports.read": "Consulter les statistiques",
  "files.read": "Consulter les fichiers",
  "files.write": "Ajouter / modifier les fichiers",
  "sync.read": "Lire la file de synchronisation",
  "sync.write": "Écrire dans la file",
  "audit.read": "Consulter le journal d'audit",
};

export const PERMISSION_CATEGORIES = [
  "CUSTOMERS",
  "ORDERS",
  "MEASUREMENTS",
  "STOCK",
  "APPOINTMENTS",
  "FINANCE",
  "TEAM",
  "TENANT",
  "REPORTS",
  "FILES",
  "SYNC",
  "AUDIT",
] as const;

export type PermissionCategory = (typeof PERMISSION_CATEGORIES)[number];

export const CATEGORY_LABELS: Record<PermissionCategory, string> = {
  CUSTOMERS: "Clients",
  ORDERS: "Commandes",
  MEASUREMENTS: "Mesures",
  STOCK: "Stock",
  APPOINTMENTS: "Rendez-vous",
  FINANCE: "Finance",
  TEAM: "Équipe",
  TENANT: "Workspace",
  REPORTS: "Statistiques",
  FILES: "Fichiers",
  SYNC: "Synchronisation",
  AUDIT: "Audit",
};

export const PERMISSION_CATEGORY_OF: Record<PermissionCode, PermissionCategory> = {
  "customers.read": "CUSTOMERS",
  "customers.write": "CUSTOMERS",
  "customers.manage": "CUSTOMERS",
  "orders.read": "ORDERS",
  "orders.write": "ORDERS",
  "orders.manage": "ORDERS",
  "measurements.read": "MEASUREMENTS",
  "measurements.write": "MEASUREMENTS",
  "stock.read": "STOCK",
  "stock.write": "STOCK",
  "fabrics.read": "STOCK",
  "fabrics.write": "STOCK",
  "appointments.read": "APPOINTMENTS",
  "appointments.write": "APPOINTMENTS",
  "payments.read": "FINANCE",
  "payments.write": "FINANCE",
  "payments.cancel": "FINANCE",
  "receipts.read": "FINANCE",
  "receipts.issue": "FINANCE",
  "team.read": "TEAM",
  "team.manage": "TEAM",
  "tenant.settings": "TENANT",
  "subscriptions.view": "TENANT",
  "reports.read": "REPORTS",
  "files.read": "FILES",
  "files.write": "FILES",
  "sync.read": "SYNC",
  "sync.write": "SYNC",
  "audit.read": "AUDIT",
};

/** Miroir exact du seed `0007_rbac.sql` (role_permissions). */
export const PERMISSIONS_BY_ROLE: Record<TenantRoleCode, readonly PermissionCode[]> = {
  OWNER: [
    "customers.read",
    "customers.write",
    "customers.manage",
    "orders.read",
    "orders.write",
    "orders.manage",
    "measurements.read",
    "measurements.write",
    "stock.read",
    "stock.write",
    "fabrics.read",
    "fabrics.write",
    "appointments.read",
    "appointments.write",
    "payments.read",
    "payments.write",
    "payments.cancel",
    "receipts.read",
    "receipts.issue",
    "team.read",
    "team.manage",
    "tenant.settings",
    "subscriptions.view",
    "reports.read",
    "files.read",
    "files.write",
    "sync.read",
    "sync.write",
    "audit.read",
  ],
  MANAGER: [
    "customers.read",
    "customers.write",
    "customers.manage",
    "orders.read",
    "orders.write",
    "orders.manage",
    "measurements.read",
    "measurements.write",
    "stock.read",
    "stock.write",
    "fabrics.read",
    "fabrics.write",
    "appointments.read",
    "appointments.write",
    "payments.read",
    "payments.write",
    "payments.cancel",
    "receipts.read",
    "receipts.issue",
    "team.read",
    "subscriptions.view",
    "reports.read",
    "files.read",
    "files.write",
    "sync.read",
    "sync.write",
    "audit.read",
  ],
  EMPLOYEE: [
    "customers.read",
    "customers.write",
    "orders.read",
    "orders.write",
    "measurements.read",
    "measurements.write",
    "stock.read",
    "fabrics.read",
    "appointments.read",
    "appointments.write",
    "payments.read",
    "receipts.read",
    "reports.read",
    "files.read",
    "files.write",
    "sync.read",
  ],
  APPRENTICE: [
    "customers.read",
    "orders.read",
    "measurements.read",
    "fabrics.read",
    "stock.read",
    "appointments.read",
    "payments.read",
    "receipts.read",
    "files.read",
    "sync.read",
  ],
};

export function can(role: TenantRoleCode, permission: PermissionCode): boolean {
  return PERMISSIONS_BY_ROLE[role].includes(permission);
}

export function permissionsFor(role: TenantRoleCode): PermissionCode[] {
  return [...PERMISSIONS_BY_ROLE[role]];
}